; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-6 on Wed Nov 11 2020 14:39:57 GMT+0800 (中国标准时间)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


