; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-6 on Wed Nov 11 2020 14:40:02 GMT+0800 (中国标准时间)
; Wait for set temperatures to be reached
M116 P0

